services:
  - type: web
    name: rag-system-api
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health